## promise
promise是用来解决callback hell的一种解决方案

- **因为Promise是一个构造函数，需要使用new来新建一个promise对象。**
- **构造函数Promise的参数是一个函数（暂时叫它func），这个函数（func）有两个参数resolve和reject，它们分别是两个函数，
这两个函数的作用就是将promise的状态从pending（等待）转换为resolved（已解决）或者从pending（等待）转换为rejected（已失败），并执行相应的处理方法**
- **创建后的promise有一些方法，then和catch。**
- **then方法接收两个函数为参数，第一个参数是处理resolved的方法，第二个是处理reject的方法，如果没有reject方法，会由catch处理**

例子详解：
``` javaScript
let p = new Promise((resolve, reject) => {
    //做一些异步操作
    setTimeout(() => {
        resolve();
    }, 1000);
});

p.then(() => {
    console.log('resolve');
},() => {
    console.log('reject');
}).catch(() => {
    console.log('catch')
});
/**
 * 打印出 resolve
 * */
p = new Promise((resolve, reject) => {
    //做一些异步操作
    setTimeout(() => {
        reject('reject');
    }, 1000);
});

p.then(() => {
    console.log('resolve');
},() => {
    console.log('reject');
}).catch(() => {
    console.log('catch')
});
/**
 * 打印出 reject
 * */

p.then(() => {
    console.log('resolve');
},).catch((message) => {
    console.log('catch ' + message)
});

/**
 * 没有reject的处理方法，就会被catch接收处理，打印出catch reject
 */
```
## promise的链式调用
- **return出一个同步的值或者undefined(即没有return语句)时，then方法将返回一个resolved状态的Promise对象，Promise对象的值就是这个返回值**
- **return 另一个 Promise，then方法将根据这个Promise的状态和值创建一个新的Promise对象返回。**

``` javaScript
let p = new Promise(function(resolve, reject){
    resolve(1);
});
p.then(function(value){               //第一个then
    console.log(value);
    return value*2;
}).then(function(value){              //第二个then
    console.log(value);
}).then(function(value){              //第三个then
    console.log(value);
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve('resolve');
        },500)
    })
}).then(function(value){              //第四个then
    console.log(value);
    return Promise.reject('reject');
}).then(function(value){              //第五个then
    console.log('resolve: '+ value);
}, function(err){
    console.log('reject: ' + err);
});
/**
 * - 上述代码 第一个then打印出1，返回状态为resolved,值为2的Promise对象,所以第二个then打印2，
 *   返回状态为resolved，值为undefined的Promise对象，所以第三个then打印出undefined,
 *   输出promise对象，处理之后，是resolved，由第四个then的成功回调函数处理，第四个then
 *   打印出resolved,返回一个状态为rejected，值为reject的Promise对象，
 *   由第五个then的失败回调函数处理，打印出reject: reject
 * */
```

### promise中关于异常的问题
_promise中一旦出现异常，会将状态变成rejected，将异常信息作为值，交由then的第二个回调函数去处理，并且在处理完成后，返回的新的Promise对象将是正常状态的，会根据状态判断是由resolved还是rejected去处理，继续去执行promise的调用链_

例子详解：
``` javaScript
let p1 = new Promise( function(resolve,reject){
    func.bar();
    resolve( 1 );
});

p1.then(
    function(value){
        console.log('resolve,value值: ' + value);
    },
    function(err){
        console.log('reject,错误信息: ' + err);
    }
).then(
    function(value){
        console.log('resolve,value值: '+value);
    },
    function(err){
        console.log('reject,错误信息: ' + err);
    }
);
/**
 * 输出如下：
 *      reject,错误信息: ReferenceError: func is not defined
 *      resolve,value值: undefined
 * */
```

## Promise.resolve()
**关于这个的理解，[八段代码彻底掌握 Promise](https://juejin.im/post/597724c26fb9a06bb75260e8)这篇文章珠玉在前，这里借鉴一下其中的代码和分析**

``` javaScript
var p1 = Promise.resolve( 1 );
var p2 = Promise.resolve( p1 );
var p3 = new Promise(function(resolve, reject){
    resolve(1);
});
var p4 = new Promise(function(resolve, reject){
    resolve(p1);
});

console.log(p1 === p2);
console.log(p1 === p3);
console.log(p1 === p4);
console.log(p3 === p4);

p4.then(function(value){
    console.log('p4=' + value);
});

p2.then(function(value){
    console.log('p2=' + value);
});

p1.then(function(value){
    console.log('p1=' + value);
});

/**
 * 输出结果：true
            false
            false
            false
            p2=1
            p1=1
            p4=1
 * */
```
 - **Promise.resolve(...)可以接收一个值或者是一个Promise对象作为参数。当参数是普通值时，它返回一个resolved状态的Promise对象，
     对象的值就是这个参数；当参数是一个Promise对象时，它直接返回这个Promise参数。因此，p1 === p2。**
 - **但通过new的方式创建的Promise对象都是一个新的对象因此后面的三个比较结果都是false。**
 - **另外，为什么p4的then最先调用，但在控制台上是最后输出结果的呢？因为p4的resolve中接收的参数是一个Promise对象p1，resolve会对p1”拆箱“，获取p1的状态和值，
     但这个过程是异步的**


``` javaScript
let p1 = new Promise(function(resolve, reject){
    resolve(Promise.resolve('resolve'));
});

let p2 = new Promise(function(resolve, reject){
    resolve(Promise.reject('reject'));
});

let p3 = new Promise(function(resolve, reject){
    reject(Promise.resolve('resolve'));
});

p1.then(
    function fulfilled(value){
        console.log('fulfilled: ' + value);
    },
    function rejected(err){
        console.log('rejected: ' + err);
    }
);

p2.then(
    function fulfilled(value){
        console.log('fulfilled: ' + value);
    },
    function rejected(err){
        console.log('rejected: ' + err);
    }
);

p3.then(
    function fulfilled(value){
        console.log('fulfilled: ' + value);
    },
    function rejected(err){
        console.log('rejected: ' + err);
    }
);

/**
 * 打印出结果：p3 rejected: [object Promise]
              p1 fulfilled: resolve
              p2 rejected: reject
 * */
```
 **Promise回调函数中的第一个参数resolve，会对Promise执行"拆箱"动作。即当resolve的参数是一个Promise对象时，
 resolve会"拆箱"获取这个Promise对象的状态和值，但这个过程是异步的。p1"拆箱"后，获取到Promise对象的状态是resolved，
 因此fulfilled回调被执行；p2"拆箱"后，获取到Promise对象的状态是rejected，因此rejected回调被执行。
 但Promise回调函数中的第二个参数reject不具备”拆箱“的能力，reject的参数会直接传递给then方法中的rejected回调。
 因此，即使p3 reject接收了一个resolved状态的Promise，then方法中被调用的依然是rejected，并且参数就是reject接收到的Promise对象。**
